version: '3.9'
services:
  notebook:
    container_name: langchaintools
    image: jupyter/datascience-notebook
    ports:
      - '8090:8090'
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - /Users/tanakatouma/vscode/langchain-tools/:/home/langchain-tools/
    command: start-notebook.sh --NotebookApp.token=''